const SOURCES = [
  { name: 'Jornal da Paraíba', feed: 'https://jornaldaparaiba.com.br/rss', search: 'https://jornaldaparaiba.com.br/tags/balneabilidade', host: 'jornaldaparaiba.com.br' },
  { name: 'F5 Online', feed: 'https://f5online.com.br/feed/', search: 'https://f5online.com.br/?s=balneabilidade', host: 'f5online.com.br' },
  { name: 'Repórter PB', feed: 'https://www.reporterpb.com.br/rss', search: 'https://www.reporterpb.com.br/?s=balneabilidade', host: 'reporterpb.com.br' },
];
const BEACHES = {
  'manaíra': 'João Pessoa', 'penha': 'João Pessoa', 'cabo branco': 'João Pessoa', 'tambaú': 'João Pessoa',
  'seixas': 'João Pessoa', 'jacarapé': 'João Pessoa', 'arraial': 'João Pessoa', 'praia do sol': 'João Pessoa',
  'maceió': 'Pitimbu', 'guarita': 'Pitimbu', 'acaú': 'Pitimbu', 'pontinha': 'Pitimbu', 'coqueiros': 'Pitimbu',
};
const normalize = (value = '') => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();
const BEACH_MAP = Object.fromEntries(Object.entries(BEACHES).map(([name, municipality]) => [normalize(name), municipality]));
const clean = (value = '') => decodeEntities(value.replace(/\s+/g, ' ').trim().replace(/^[\s•–—-]+|[\s•–—-]+$/g, ''));
function decodeEntities(value) { return value.replace(/<!\[CDATA\[|\]\]>/g, '').replace(/&nbsp;/g, ' ').replace(/&amp;/g, '&').replace(/&#39;|&apos;/g, "'").replace(/&quot;/g, '"').replace(/&#x([0-9a-f]+);/gi, (_, hex) => String.fromCodePoint(parseInt(hex, 16))).replace(/&#(\d+);/g, (_, code) => String.fromCodePoint(Number(code))); }
async function get(url) { const response = await fetch(url, { headers: { 'user-agent': 'VivaJoaoPessoa/1.0' } }); if (!response.ok) throw new Error(`${response.status} ${url}`); return response.text(); }
function stripHtml(value) { return decodeEntities(value.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>|<noscript[\s\S]*?<\/noscript>/gi, '').replace(/<[^>]+>/g, '\n')).split(/\n+/).map(line => line.replace(/\s+/g, ' ').trim()).filter(Boolean).join('\n'); }
function feedEntries(xml) { return [...xml.matchAll(/<item[\s\S]*?<\/item>/gi)].map(match => { const item = match[0]; const read = tag => clean((item.match(new RegExp(`<${tag}(?:[^>]*)>([\\s\\S]*?)<\\/${tag}>`, 'i')) || [,''])[1]); return { title: read('title'), url: decodeEntities((item.match(/<link>([\s\S]*?)<\/link>/i) || [,''])[1].trim()), published: read('pubDate') }; }); }
function articleLinks(html, host) { return [...html.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)].map(match => ({ url: new URL(match[1], `https://${host}`).href, title: stripHtml(match[2]) })).filter(item => item.url.includes(host) && item.title.length > 20 && /balneabilidade|praias? impróprias?|praias? improprias?|impróprios? para banho|improprios? para banho/i.test(`${item.title} ${item.url}`)); }
function findMetadata(text) { const period = (text.match(/(?:coletou amostras|amostras? realizadas?)[^\n.]{0,100}?(\d{1,2}\s+de\s+\w+\s+(?:a|e)\s+\d{1,2}\s+de\s+\w+)/i) || text.match(/(?:período|periodo)[^\n.]{0,60}(\d{1,2}\s+de\s+\w+\s+a\s+\d{1,2}\s+de\s+\w+)/i) || [,''])[1]; const validade = (text.match(/(?:válid[oa]|validade)[^\n.]{0,80}(?:até|dia)\s+(?:a próxima sexta-feira \()?([0-9]{1,2}(?:\s+de\s+\w+)?)/i) || [,''])[1]; return { periodo: clean(period), validade: clean(validade) }; }
function extractRecords(text) { const records = []; const add = (praia, point) => { const ponto = clean(point), municipality = BEACH_MAP[normalize(praia)]; if (municipality && ponto && !/própria|liberada|monitorada/i.test(ponto)) records.push({ municipio: municipality, praia, ponto, qualidade: 'Imprópria' }); }; for (const match of text.matchAll(/([^\n:]{2,50}):\s*([^\n]{3,150})/g)) add(clean(match[1]), match[2]); for (const praia of Object.keys(BEACHES)) { const escaped = praia.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); const match = text.match(new RegExp(`${escaped}\\s*:\\s*([^\\n:]{3,150})`, 'i')); if (match) add(praia, match[1]); } return [...new Map(records.map(record => [`${normalize(record.municipio)}|${normalize(record.praia)}|${normalize(record.ponto)}`, record])).values()]; }
async function discover(source) { const matches = []; try { for (const entry of feedEntries(await get(source.feed)).slice(0, 80)) if (/balneabilidade|praias? impróprias?|praias? improprias?|impróprios? para banho|improprios? para banho/i.test(`${entry.title} ${entry.url}`)) matches.push(entry); } catch {} if (!matches.length) { try { matches.push(...articleLinks(await get(source.search), source.host)); } catch {} } return matches; }
export async function collect() { const articles = [], statuses = []; for (const source of SOURCES) { try { const matches = await discover(source); if (matches.length) { const article = matches[0]; const text = stripHtml(await get(article.url)); const meta = findMetadata(text); articles.push({ source: source.name, title: article.title, url: article.url, published: article.published || '', ...meta, records: extractRecords(text) }); } statuses.push({ name: source.name, found: Boolean(matches.length), articles: matches.length, error: null }); } catch (error) { statuses.push({ name: source.name, found: false, articles: 0, error: error.message }); } } const groups = new Map(); for (const article of articles) for (const record of article.records) { const id = `${normalize(record.municipio)}|${normalize(record.praia)}|${normalize(record.ponto)}`; const group = groups.get(id) || { ...record, sources: [] }; if (!group.sources.includes(article.source)) group.sources.push(article.source); groups.set(id, group); } const records = [...groups.values()].map(record => ({ ...record, confidence: record.sources.length >= 2 ? 'alta' : 'revisar' })); const periods = articles.map(a => a.periodo).filter(Boolean), validities = articles.map(a => a.validade).filter(Boolean); return { generated_at: new Date().toISOString(), periodo: periods[0] || null, validade: validities[0] || null, confidence: records.length && records.every(r => r.confidence === 'alta') ? 'alta' : 'revisar', records, articles, sources: statuses, official_reference: 'https://sudema.pb.gov.br/qualidade-do-ambiente/relatorios-de-balneabilidade', official_reference_automated: false }; }
